In [1]:
#import library numpy
import numpy as np

In [2]:
#Create a NumPy ndarray Object
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Access Array Elements
print(arr[0]) 

1


In [4]:
#Slicing arrays
#[start:end:step].
print(arr[1:5]) 

[2 3 4 5]


In [5]:
#Data Types in Python
print(arr.dtype) 

int32


In [6]:
#The Difference Between Copy and View
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
#Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 



(2, 4)


In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [9]:
#Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#Reshape From 1-D to 3-D
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
#Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

1
2
3


In [12]:
#Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [13]:
#Joining NumPy Arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [14]:
#Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#Splitting NumPy Arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
#Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6], dtype=int64),)


In [18]:
#Sorting Arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [19]:
#Sort the array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [20]:
#Sort a boolean array
arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


In [21]:
#Sort a 2-D array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [22]:
#Filtering Arrays
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [23]:
#Creating the Filter Array
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False, False, True, True]
[43 44]


In [24]:
#Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False, True, False, True, False, True, False]
[2 4 6]
